spring:
  datasource:
    url: jdbc:h2:mem:library
    initialization-mode: never

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: false

    show-sql: false

logging:
  level:
    ROOT: ERROR